on:
  schedule:
    - cron:  '* * * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

name: Scrape Data
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: pip3 install -r requirements.txt
    - name: Scrape
      run: python3 injuries.py
      # env:
      #   WHATEVER_TOKEN: ${{ secrets.YOU_WANT }}
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you

name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps: pip3 install -r requirements.txt && python3 injuries.py
    - name: Check out this repo
      uses: actions/checkout@v2
    # - name: Fetch latest data
    #   run:
#     - name: Commit and push if it changed
#       run: |-
#         git config user.name "Automated"
#         git config user.email "actions@users.noreply.github.com"
#         git add -A
#         timestamp=$(date -u)
#         git commit -m "Latest data: ${timestamp}" || exit 0
#         git push